// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
int add_int(int a, int b);
extern "C" SEXP _mode_add_int(SEXP a, SEXP b) {
  BEGIN_CPP11
    return cpp11::as_sexp(add_int(cpp11::as_cpp<cpp11::decay_t<int>>(a), cpp11::as_cpp<cpp11::decay_t<int>>(b)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_mode_add_int", (DL_FUNC) &_mode_add_int, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_mode(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
